name: ctos
description: Personal Android network observatory and terminal with Vector integration.
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.9.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  xterm: 4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
